default_stages: [pre-commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 5888d1c64e8d11186b79075ea7a4e893a7e72c72
    hooks:
      - id: astyle-c-in
      - id: shfmt

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
      - id: clang-format

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        stages: [pre-commit]

      # Python only
      - id: debug-statements

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
